### ISSUE TITLE
Ajouter un domaine personnalisé

### ISSUE THREAD

**Issue by bertrandbo** [alionetasso/opensuse-guide-fr#2]
Bonjour,

Au lieu d'utiliser le domaine Github pour le site généré, est-il envisageable d'avoir un sous-domaine sur alionet.org pour exposer ce guide ?

Par exemple, `guide.alionet.org` et/ou `debutant.alionet.org` ?

Cela éviterait la dispersion dans la communication je pense (tout le francophone chez alionet et non une partie chez alionet, une autre chez Github, etc) tout en étant plus cohérent avec `blog.alionet.org`

A titre d'information, la documentation Github Pages sur les domaines personnalisés se trouve [ici](https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site).

Merci

**Comment by sjpp** [comment]
Salut,
Oui c'est pas faux, ça améliorerait la cohérence de l'ensemble.
@CChalu : une préférence pour le nom de domaine ?

* guide.alionet.org
* debutant.alionet.org
* guide-debutant.alionet.org
* obiwankenobi.alionet.org 

?

Ne me laisser pas choisir sinon ce sera le 4ème :smiley:

**Comment by CChalu** [comment]
Salut :)
Alors le 4) me tente beaucoup aussi ;)
Est-ce que ce serait réutilisable pour d'autres travaux également, type rédaction d'un tuto sur un truc ?
dans ce cas peut-être le #2
ou alors docs.alionet.org ?
ça ferait
www.docs.alionet.org/opensuse_guide-fr
www.docs.alionet.org/tuto-de-la-mort

**Comment by sjpp** [comment]
Pour les tutos on a le forum ou, de préférence, un article dans le blog.
Non la l'idée c'est que:

https://alionetasso.github.io/opensuse-guide-fr/

devienne

https://guide-debutant.alionet.org/

(tout court)

**Comment by CChalu** [comment]
ok donc si ça ne peut pas servir pour d'autres choses donc autant effectivement mettre
guide-opensuse.alionet.org
c'est bête de perdre opensuse dans l'adresse

**Comment by sjpp** [comment]
Ça me va comme ça, je fais ça.

**Comment by sjpp** [comment]
Done: https://guide-opensuse.alionet.org
